lane :test do
    carthage(
        command: "update",
        use_submodules: true,
        no_build: true,
        verbose: true,
        platform: "Mac,iOS"
    )
    scan(
        workspace: "MDWamp.xcworkspace",
        scheme: "MDWamp iOS",
        clean: true
    )
end

lane :bump do  |options|
    increment_version_number(
        bump_type: options[:bump],        
        xcodeproj: 'MDWamp.xcodeproj'
    )
    version = get_version_number(xcodeproj: "MDWamp.xcodeproj")
    version_bump_podspec(path: "MDWamp.podspec", version_number: version)
    git_commit(
        path: ["Sources/Info-OSX.plist", "Sources/Info-iOS.plist", "MDWamp Demo/Info.plist", "MDWamp iOSTests/Info.plist", "MDWamp.podspec"],
        message: changelog_from_git_commits
    )
    add_git_tag(
        tag: get_version_number(xcodeproj: "MDWamp.xcodeproj")
    )
end

lane :check do
    pod_lib_lint(allow_warnings: true, verbose: true)
end